### ISSUE TITLE
Support for go-ipfs v0.5

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/py-ipfs-http-client#204]
> This is a notice I'm filling in repo of every HTTP Client I can find.
> **Feel free to close it if this project already works fine with go-ipfs 0.5**

## POST-only HTTP API

go-ipfs 0.5  will block `GET` commands on the API port (https://github.com/ipfs/go-ipfs/pull/7097), requiring every  command (RPC) to be sent as HTTP `POST` request.
See API reference docs: https://docs.ipfs.io/reference/api/http/

**This is potentially a breaking change**, 
double check if this project uses `POST` for every RPC call.

## Testing 

Download links for v0.5-rc* are available at https://github.com/ipfs/go-ipfs/issues/7109

You can also test using an ephemeral Docker container:

```console
$ docker run --rm -it --net=host ipfs/go-ipfs:v0.5.0-rc1 
```

**Comment by alexander255** [comment]
Thanks for the heads-up! I'm in the process of finally releasing a version again (the last to support Python 2.7 & 3.4). After this I'll do some testing on this since it will not certainly need patches if it's now POST-only.

Do you know by any chance if similar disruptive changes are planned for future 0.x release (0.6, 0.7, …), because in that case I'll keep locking *py-ipfs-http-client* releases to the respective go-ipfs minor versions.

**Comment by alexander255** [comment]
Also, do you know why this repo was moved to ipfs-shipyard?

**Comment by alexander255** [comment]
Support for this is now on `master`!

**Comment by ibnesayeed** [comment]
> @@alexander255: Support for this is now on master!

Now that IPFS 0.5 is publicly released, do we have an ETA of when will the next version be released on PyPI with this fix? While we have added IPFS 0.5 support in IPWB using the master branch as a temporary fix as https://github.com/oduwsdl/ipwb/pull/641, we are waiting for this client (that we heavily rely on) to be updated before we release a new version.

**Comment by alexander255** [comment]
Thanks for the heads up! I'll try to get the changes planned for py-ipfs-api-client done by the end of this week!

**Comment by momack2** [comment]
Thanks @alexander255 - any update on that timeline?

**Comment by ibnesayeed** [comment]
@ntninja is there anything specific that is holding a new release up? Do you need any help?

**Comment by machawk1** [comment]
@momack2 Are you aware of any movement on ipfshttpclient releasing a new version? We had to fork and publish to PyPI at https://pypi.org/project/ipfshttpclient4ipwb/ because PyPI does not allow direct pinning (e.g., to py-ipfs-http-client master branch) and we have needed a new version of this module pushed to PyPI for https://github.com/oduwsdl/ipwb. We are hoping to revert back to basing our code on py-ipfs-http-client but cannot rely on the current master or a particular commit for this module -- it needs to be a release.
