### ISSUE TITLE
Python 3.5 is past EOL; Drop Support

### ISSUE THREAD

**Issue by c0llab0rat0r** [ipfs-shipyard/py-ipfs-http-client#258]
Drop support for Python 3.5 by raising the minimum version to 3.6 (EOL this year) or 3.7 (EOL 2023).

This will make fixing the typing and type linting easier.

The code base currently has syntax that is not valid in 3.5, such as this at https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/0.7.0/ipfshttpclient/http_httpx.py#L41

    def map_args_to_httpx(
        *,
        auth: auth_t = None,
        cookies: cookies_t = None,
        headers: headers_t = None,
        params: params_t = None,
        timeout: timeout_t = None,
    ) -> RequestArgs:

**Comment by c0llab0rat0r** [comment]
If #260 is merged, it would resolve this issue.

**Comment by ntninja** [comment]
The post-EOL compatibility with Python 3.5 is intentional since this project pledged support for Ubuntu 16.04LTS for servers. That will be EOL the end of this month, so dropping 3.5 is OK. Support for 3.6 is still necessary – in general this library does intend to be appealing to a large audience, so premature deprecation is a no-go.

The quoted piece of source code is not used in Python 3.5 btw, so it's lot like “Python 3.5 is already broken anyways” (this part of CI is still functional).

**Comment by ntninja** [comment]
This you have fixed as well now!
