### ISSUE TITLE
Looking for a maintainer familiar with Python! 🙏

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/py-ipfs-http-client#316]
This project needs a maintainer that will ensure this library works with Kubo RPC (https://docs.ipfs.tech/reference/kubo/rpc/)

Kubo team will be maintaining [GO](https://github.com/ipfs/kubo/issues/9124) and [JS](https://github.com/ipfs/kubo/issues/9125) libraries, but we need someone familiar with Python to step up and help with this one.

If you are interested, please comment below.

**Comment by lablnet** [comment]
Interested

**Comment by DobleV55** [comment]
Hi, I would like to help!

**Comment by willcharlton** [comment]
Interested

**Comment by hemangjoshi37a** [comment]
I am interested in maintaining this library

**Comment by Wizock** [comment]
I'm also interested, my work-around to integrating ipfs in my python app is kind of tedious to work with :( please let me know if I can do anything to help out

**Comment by JustinGirard** [comment]
Yo I need to use this library and I think its version check code just died. I can perhaps take a look. (I fixed it for myself personally, by removing the version check, which is just horrid, but I am willing to take a deeper gander.)

**Comment by lidel** [comment]
Hi all, firstly, I apologize for missing notifications on this.

I've granted maintenance permissions to @kasteph who will be taking over this, 
and will coordinate sharing maintenance with anyone who has time to help. :pray:

**Comment by kasteph** [comment]
Hey @willcharlton @JustinGirard @hemangjoshi37a @Wizock -- I'm working on https://github.com/ipfs-shipyard/py-ipfs-http-client/pull/320 at the moment. This PR will probably be bigger than expected as we need to address a lot of breaking changes since then. Let me know if you have capacity and what you'd be interested on working with then we can coordinate.

**Comment by kasteph** [comment]
Awesome @Wizock -- to start with, I think reviewing the open PRs and seeing if any of them are still relevant would be a huge help. Otherwise, I will assign you to an issue that addresses the `pubsub`.

**Comment by Wizock** [comment]
@kasteph awesome I'll get started on that right now.

**Comment by ntninja** [comment]
Sorry for the long silence!

I just wanted to write here to confirm that I will no longer be taking part in any development activities regarding py-ipfs-api-client. Things have changed a lot since I last did anything in early 2021 and its become very obvious that I will no longer be spending much time on software outside of my tutoring job. I know there have been communication attempts regarding this subject before (particularly regarding ownership of the PyPI project), but I hadn’t really been prepared to hand off this project for good yet…

So what I’m saying is: Just let me know what you need in terms of permissions and handover and I’ll be responsive regarding that now. If there is any questions regarding the existing codebase I can answer those as well. You can also remove my permissions from this repository as I’ll no longer be using them.

(Also: Sorry to everyone having been stuck on go-ipfs 0.7.0 or having to maintain their own fork because of this!)

Sincerely,
Erin

**Comment by ntninja** [comment]
@hemangjoshi37a: I was actually hoping to hand this over to someone with prior experience of the codebase (at least a sensible open PR or something) and your request does feel pretty… random. I could be missing something obvious here, but do you have any affiliation with this project at all? Or someone to vouch for you?

**Comment by hemangjoshi37a** [comment]
@ntninja I use AI agents to code so I don't need to understand anything. They will understand for me and code for me. Software programming is dead anyways killed by agentic workflow. If you don't know what I am talking about then you are living in the stone age.

**Comment by eldoradomap** [comment]
bro wtf happened to the end of this thread 💀

**Comment by crushr3sist** [comment]
> bro wtf happened to the end of this thread 💀

mad cringe tbh
